logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
server:
  port: 8090
base-url: http://localhost:${server.port} 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/   
keycloak-client:
  server-url: '{cipher}e1e5a1ddf8af26a44ffca2d8633ec5ac5e3a08467594ca4cffedb03cb9e2c8a79943d19f9751020fc78d4af79aa3cd52'
  realm:  mydev
spring:
  application:
    name: api-gateway 
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: api-gateway
            client-secret: T7OuUKKsJMnrPOyn5CgfYcKr2QuuNi8I
            authorization-grant-type: authorization_code
            redirect-uri: ${base-url}/login/oauth2/code/keycloak
            scope: openid
        provider:
          keycloak:
            authorization-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
            user-name-attribute: name
            user-info-authentication-method: header
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
          issuer-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}
  cloud:
    gateway: 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
            - PATCH
            - OPTIONS
            add-to-simple-url-handler-mapping: true
      routes:
        - id: egis0-service
          uri: lb://egis0-service
          predicates:
            - Path=/egis0-api/**
            - Method=GET,POST,DELETE,PUT,PATCH,OPTIONS
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: jd0-service
          uri: lb://jd0-service
          predicates:
            - Path=/jd0-api/**
            - Method=GET,POST,DELETE,PUT,PATCH,OPTIONS
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie            
        - id: prot0-service
          uri: lb://prot0-service
          predicates:
            - Path=/prot0-api/**
            - Method=GET,POST,DELETE,PUT,PATCH,OPTIONS
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            
