server:
  port: 8092
  servlet:
    context-path: /realtime    
base-url: http://localhost:${server.port}/${server.servlet.context-path}  
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/ 
keycloak-client:
  server-url: '{cipher}648f5641949f2730f5e80f091f6f86e873ef869f6aa24764ead03054ede547945195419334792b8076d2741bfe45f3cb'
  realm:  Smartcity
    
spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: realtime-service
            client-secret: f127b769-f8f8-44e0-af16-735497f677d5
            authorization-grant-type: authorization_code
            redirect-uri: ${base-url}/login/oauth2/code/keycloak
            scope: openid
        provider:
          keycloak:
            authorization-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
            user-name-attribute: name
            user-info-authentication-method: header
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs    
  
app:
  kafka:
    bootstrap-servers: '{cipher}523ef3efed78f2241eed3894404d5a092f0ec2e135fb1416ce12e1fb1c5674154c584acd62f1b3e5602bcf279d9cbe7e'
    consumer:
      group-id: iot
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.jdvn.smartcity.tamky.util.TemperatureSensorDataMessageDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.jdvn.smartcity.tamky.util.TemperatureSensorDataMessageSerializer
    topic:
      temperature-sensor: TrackTemperature

  influxdb:
    url: '{cipher}2353ecb7967271096366e03503a5f2c4dd3326d0aaa384d30163d963b1a82d1fef8e80c4c30ee683cbafad33fedfb8af'
    user: '{cipher}67d998b6d6842f0f821f858f43a7ff1f5848481d058b308622b7f47f1ca57abb'
    pass: '{cipher}438a7a478ea9a3b720c964360f2d81a9f8c59953330ed41c465b950f8a2635e8'
    database: sensordata
    retention-policy: autogen
    read-timeout-in-seconds: 100
  
logging:
  level:
    root: INFO
    com.jdvn.smartcity.tamky: DEBUG
